### ISSUE TITLE
whx

### ISSUE THREAD

**Issue by Muffinmaker2** [P-DennyGamingYT/ALCATRAZ-PF#1]
u skid?

**Comment by CallMeBurb2** [comment]
yeah lmao its just a purple haze skid

**Comment by P-DennyGamingYT** [comment]
its an upgraded version.

**Comment by RealMuffinmaker** [comment]
no it's not upgraded

**Comment by paysonism** [comment]
I added all guns, fixed fov. And I’m adding esp soon

**Comment by RealMuffinmaker** [comment]
no u are not everything is already there u skid
